title: winnie xu.
description: Just a human, being.
github_username: xwinxu

# Email and twitter are optional:
email: winnie@for.ai
twitter_username: winniethexu

# Set this to true to get LaTeX math equation support
use_math: true 

# Everything below here can be ignored, unless you want to change the theme entirely
theme: minima
plugins:
  - jekyll-feed
  - jekyll-octicons

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
